services:
  - type: web
    name: swap-portfolio
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    disk:
      name: sqlite-data
      mountPath: /opt/api/data
      sizeGB: 1
    envVars:
      - key: CORS_ORIGIN
        sync: false
      - key: IP_SALT
        generateValue: true
      - key: PORT
        value: 3000
